services:
  frontend:
    container_name: afterlife-frontend
    image: $CI_REGISTRY_IMAGE/frontend:$TAG
    ports:
      - 80:80
      - 443:443
    stdin_open: true
    volumes:
      - ./client/src:/app/src
#      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: afterlife-backend
    image: $CI_REGISTRY_IMAGE/backend:$TAG
    restart: always
    volumes:
      #- ./server/uploads:/home/afterlife/uploads
      - /home/afterlife/volumes/server/uploads:/app/uploads
#      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 5000
  mongo:
    container_name: afterlife-mongodb
    restart: always
    image: mongo:7.0
    volumes:
      - /home/afterlife/volumes/mongo:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    # ports:
    #   - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: $CI_MONGO_INITDB_ROOT_USERNAME
    #   MONGO_INITDB_ROOT_PASSWORD: $CI_MONGO_INITDB_ROOT_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: afterlife
      ME_CONFIG_MONGODB_ADMINPASSWORD: afterlife1234
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
networks:
  react-express:
  express-mongo:
